FROM mcr.microsoft.com/dotnet/aspnet:8.0.2 AS base
WORKDIR /src

RUN adduser --disabled-password --gecos '' amorphie-workflowuser && chown -R amorphie-workflowuser:amorphie-workflowuser /src
USER amorphie-workflowuser

FROM mcr.microsoft.com/dotnet/sdk:8.0.200 AS build
WORKDIR /src
ENV DOTNET_NUGET_SIGNATURE_VERIFICATION=false
COPY ["./amorphie.workflow.hzconsumer/amorphie.workflow.hzconsumer.csproj", "."]
RUN dotnet restore "./amorphie.workflow.hzconsumer.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./amorphie.workflow.hzconsumer/amorphie.workflow.hzconsumer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./amorphie.workflow.hzconsumer/amorphie.workflow.hzconsumer.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /src
COPY --from=publish /app/publish .
EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "amorphie.workflow.hzconsumer.dll"]
