FROM test-nexusapi-amorphie.apps.nonprod.ebt.bank/repository/amorphie/mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

RUN adduser -u 5679 --disabled-password --gecos "" amorphie-workflow-hubuser && chown -R amorphie-workflow-hubuser:amorphie-workflow-hubuser /app
USER amorphie-workflow-hubuser

FROM test-nexusapi-amorphie.apps.nonprod.ebt.bank/repository/amorphie/mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["./amorphie.workflow.hub/amorphie.workflow.hub.csproj", "."]
RUN dotnet restore "./amorphie.workflow.hub.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./amorphie.workflow.hub/amorphie.workflow.hub.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./amorphie.workflow.hub/amorphie.workflow.hub.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "amorphie.workflow.hub.dll"]
