apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: workflow-secretstore
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: https://cxxxxxxx
    - name: vaultToken
      value: "yyyyyyyyyyy"
    - name: skipVerify
      value: true
    - name: vaultKVUsePrefix
      value: false
    - name: enginePath
      value: "dev-amorphie-workflow"
