apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: workflow-secretstore
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: https://10.180.141.16:32478
    - name: vaultToken
      value: "hvs.mn9I4IAwF8JcWFkBeEQm6b09"
    - name: skipVerify
      value: true
    - name: vaultKVUsePrefix
      value: false
    - name: enginePath
      value: "dev-amorphie-workflow"